/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplologin.vista;

import ejemplologin.controlador.ControladorLogin;
import ejemplologin.controlador.ControladorUniversidad;
import ejemplologin.excepciones.UniversidadExcepcion;
import ejemplologin.modelo.Materia;
import ejemplologin.modelo.Usuario;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carloaiza
 */
public class MDIEjemploLogin extends javax.swing.JFrame {

    private ControladorLogin controlLogin;
    private Usuario usuarioAutenticado;
    private ControladorUniversidad controlUniversidad;

    /**
     * Creates new form MDIEjemploLogin
     */
    public MDIEjemploLogin() {
        initComponents();

    }

    private void iniciarMenus(boolean estado) {
        mnuCrearEstudiante.setVisible(estado);
        mnuListarEstudiantes.setVisible(estado);
        mnuMaterias.setVisible(estado);
        mnuCrearMateria.setVisible(estado);
        mnuListarMaterias.setVisible(estado);
        mnuMaterias.setVisible(estado);
    }

    private void gestionarPermisosMenu() {

        switch (usuarioAutenticado.getTipoUsuario().getCodigo()) {
            ///administrador
            case 1:
                iniciarMenus(true);
                break;
            ///consulta
            case 2:
                iniciarMenus(false);
                mnuListarEstudiantes.setVisible(true);
                mnuMaterias.setVisible(true);
                mnuListarMaterias.setVisible(true);
                break;
            ///Secretaria
            case 3:
                iniciarMenus(false);
                mnuListarEstudiantes.setVisible(true);
                mnuMaterias.setVisible(true);
                mnuListarMaterias.setVisible(true);
                mnuCrearEstudiante.setVisible(true);
                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jfrmLogin = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jifMaterias = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaterias = new javax.swing.JTable();
        lblCodigoMateria = new javax.swing.JLabel();
        lblNombreMateria = new javax.swing.JLabel();
        lblCapacidadMateria = new javax.swing.JLabel();
        spnCapacidadMateria = new javax.swing.JSpinner();
        txtCodigoMateria = new javax.swing.JTextField();
        txtNombreMateria = new javax.swing.JTextField();
        btnGuardarMateria = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        mnuEjercicioLogin = new javax.swing.JMenu();
        mnuCrearEstudiante = new javax.swing.JMenuItem();
        mnuListarEstudiantes = new javax.swing.JMenuItem();
        mnuMaterias = new javax.swing.JMenu();
        mnuCrearMateria = new javax.swing.JMenuItem();
        mnuListarMaterias = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jfrmLogin.setTitle("Login");
        jfrmLogin.setVisible(true);

        jLabel1.setText("*Correro Eletrónico:");

        jLabel2.setText("*Contraseña:");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfrmLoginLayout = new javax.swing.GroupLayout(jfrmLogin.getContentPane());
        jfrmLogin.getContentPane().setLayout(jfrmLoginLayout);
        jfrmLoginLayout.setHorizontalGroup(
            jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmLoginLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtCorreo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmLoginLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(btnIngresar)
                .addGap(240, 240, 240))
        );
        jfrmLoginLayout.setVerticalGroup(
            jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmLoginLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnIngresar)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        desktopPane.add(jfrmLogin);
        jfrmLogin.setBounds(20, 30, 570, 310);

        jifMaterias.setClosable(true);
        jifMaterias.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifMaterias.setIconifiable(true);
        jifMaterias.setMaximizable(true);
        jifMaterias.setResizable(true);
        jifMaterias.setTitle("Listado de Materias");
        jifMaterias.setToolTipText("");
        jifMaterias.setVisible(false);

        tblMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Capacidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMaterias);

        lblCodigoMateria.setText("Código: * ");

        lblNombreMateria.setText("Nombre: *");

        lblCapacidadMateria.setText("Capacidad:");

        btnGuardarMateria.setText("Agregar Materia");
        btnGuardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifMateriasLayout = new javax.swing.GroupLayout(jifMaterias.getContentPane());
        jifMaterias.getContentPane().setLayout(jifMateriasLayout);
        jifMateriasLayout.setHorizontalGroup(
            jifMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifMateriasLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jifMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifMateriasLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnGuardarMateria))
                    .addGroup(jifMateriasLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jifMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigoMateria)
                            .addComponent(lblNombreMateria)
                            .addComponent(lblCapacidadMateria))
                        .addGroup(jifMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jifMateriasLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(spnCapacidadMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jifMateriasLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jifMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jifMateriasLayout.setVerticalGroup(
            jifMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifMateriasLayout.createSequentialGroup()
                .addGroup(jifMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifMateriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jifMateriasLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jifMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoMateria)
                            .addComponent(txtCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jifMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreMateria)
                            .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jifMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCapacidadMateria)
                            .addComponent(spnCapacidadMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarMateria)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        desktopPane.add(jifMaterias);
        jifMaterias.setBounds(300, 50, 630, 340);

        mnuEjercicioLogin.setMnemonic('f');
        mnuEjercicioLogin.setText("Archivo");
        mnuEjercicioLogin.setEnabled(false);

        mnuCrearEstudiante.setMnemonic('o');
        mnuCrearEstudiante.setText("Crear Estudiante");
        mnuEjercicioLogin.add(mnuCrearEstudiante);

        mnuListarEstudiantes.setMnemonic('s');
        mnuListarEstudiantes.setText("Listar Estudiantes");
        mnuEjercicioLogin.add(mnuListarEstudiantes);

        mnuMaterias.setText("Materias");

        mnuCrearMateria.setMnemonic('a');
        mnuCrearMateria.setText("Crear Materia");
        mnuMaterias.add(mnuCrearMateria);

        mnuListarMaterias.setText("Listar Materias");
        mnuListarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarMateriasActionPerformed(evt);
            }
        });
        mnuMaterias.add(mnuListarMaterias);

        mnuEjercicioLogin.add(mnuMaterias);

        mnuCerrarSesion.setText("Cerrar Sesión");
        mnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarSesionActionPerformed(evt);
            }
        });
        mnuEjercicioLogin.add(mnuCerrarSesion);

        mnuSalir.setMnemonic('x');
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuEjercicioLogin.add(mnuSalir);

        menuBar.add(mnuEjercicioLogin);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:

        if (txtCorreo.getText() == null || txtCorreo.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe diligenciar el correo", "Datos Faltantes", 2);
        } else if (txtContrasenia.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe diligenciar la contraseña", "Datos Faltantes", 2);
        } else {
            controlLogin = new ControladorLogin();

            //Significa que diligencio correo y contraseña
            Pattern pattern = Pattern.compile("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$");
            Matcher matcher = pattern.matcher(txtCorreo.getText());

            if (matcher.find() == true) {
                usuarioAutenticado = controlLogin.
                        encontrarUsuario(txtCorreo.getText(), txtContrasenia.getText());
                if (usuarioAutenticado == null) {
                    JOptionPane.showMessageDialog(this,
                            "El usuario Ingresado no existe", "Datos Erróneos", 0);
                } else {
                    controlUniversidad = new ControladorUniversidad();

                    JOptionPane.showMessageDialog(this,
                            "Bienvenido " + usuarioAutenticado, "Bienvenido", 1);
                    mnuEjercicioLogin.setEnabled(true);
                    gestionarPermisosMenu();
                    jfrmLogin.hide();
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "El correo no tiene un formato válido", "Datos Erróneos", 0);

            }

        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSesionActionPerformed
        // TODO add your handling code here:
        mnuEjercicioLogin.setEnabled(false);
        txtCorreo.setText("");
        txtContrasenia.setText("");
        usuarioAutenticado = null;
        iniciarMenus(false);
        jfrmLogin.show();

    }//GEN-LAST:event_mnuCerrarSesionActionPerformed

    private void pintarMaterias() {
        DefaultTableModel model = (DefaultTableModel) tblMaterias.getModel();
        model.getDataVector().removeAllElements();
        for (Materia materia : controlUniversidad.getMaterias()) {
            model.addRow(materia.obtenerArregloObjeto());
        }
        tblMaterias.setModel(model);

    }


    private void mnuListarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarMateriasActionPerformed
        // TODO add your handling code here:
        controlUniversidad.llenarMaterias();
        pintarMaterias();
        jifMaterias.repaint();
        jifMaterias.show();
        if (jifMaterias.isIcon()) {
            try {
                jifMaterias.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(MDIEjemploLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnuListarMateriasActionPerformed

    private void btnGuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMateriaActionPerformed
        // TODO add your handling code here:
        if (txtCodigoMateria.getText() == null || txtCodigoMateria.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe diligenciar el código de la Materia", "Datos Faltantes", 2);
        } else if (txtNombreMateria.getText() == null || txtNombreMateria.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe diligenciar el nombre de la materia", "Datos Faltantes", 2);
        } else {
            byte capacidad = Byte.parseByte(spnCapacidadMateria.getValue().toString());
            Materia mat = new Materia(txtCodigoMateria.getText(), txtNombreMateria.getText(),
                    capacidad);
            try {
                controlUniversidad.adicionarMateria(mat);
                pintarMaterias();
                txtCodigoMateria.setText("");
                txtNombreMateria.setText("");
                spnCapacidadMateria.setValue(0);
            } catch (UniversidadExcepcion ex) {
               JOptionPane.showMessageDialog(this,
                   ex.getMessage() , "Error en materia", 0);
            }

        }
    }//GEN-LAST:event_btnGuardarMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIEjemploLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIEjemploLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIEjemploLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIEjemploLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIEjemploLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarMateria;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JInternalFrame jfrmLogin;
    private javax.swing.JInternalFrame jifMaterias;
    private javax.swing.JLabel lblCapacidadMateria;
    private javax.swing.JLabel lblCodigoMateria;
    private javax.swing.JLabel lblNombreMateria;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenuItem mnuCrearEstudiante;
    private javax.swing.JMenuItem mnuCrearMateria;
    private javax.swing.JMenu mnuEjercicioLogin;
    private javax.swing.JMenuItem mnuListarEstudiantes;
    private javax.swing.JMenuItem mnuListarMaterias;
    private javax.swing.JMenu mnuMaterias;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JSpinner spnCapacidadMateria;
    private javax.swing.JTable tblMaterias;
    private javax.swing.JTextField txtCodigoMateria;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables

}
