/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplologin.vista;

import ejemplologin.controlador.ControladorLogin;
import ejemplologin.modelo.Usuario;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author carloaiza
 */
public class MDIEjemploLogin extends javax.swing.JFrame {

    private ControladorLogin controlLogin;
    private Usuario usuarioAutenticado;

    /**
     * Creates new form MDIEjemploLogin
     */
    public MDIEjemploLogin() {
        initComponents();
        controlLogin = new ControladorLogin();

    }
    
    private void iniciarMenus(boolean estado)
    {
        mnuCrearEstudiante.setVisible(estado);
        mnuListarEstudiantes.setVisible(estado);
        mnuMaterias.setVisible(estado);
        mnuCrearMateria.setVisible(estado);
        mnuListarMaterias.setVisible(estado);
        mnuMaterias.setVisible(estado);
    }
    
    private void gestionarPermisosMenu()
    {
        
        switch(usuarioAutenticado.getTipoUsuario().getCodigo())
        {
            ///administrador
            case 1:
                iniciarMenus(true);
                break;
            ///consulta
            case 2:            
                iniciarMenus(false);
                mnuListarEstudiantes.setVisible(true);
                mnuMaterias.setVisible(true);
                mnuListarMaterias.setVisible(true);
                break; 
            ///Secretaria
            case 3:
                iniciarMenus(false);
                mnuListarEstudiantes.setVisible(true);
                mnuMaterias.setVisible(true);
                mnuListarMaterias.setVisible(true);
                mnuCrearEstudiante.setVisible(true);
                break;
            
                
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jfrmLogin = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        mnuEjercicioLogin = new javax.swing.JMenu();
        mnuCrearEstudiante = new javax.swing.JMenuItem();
        mnuListarEstudiantes = new javax.swing.JMenuItem();
        mnuMaterias = new javax.swing.JMenu();
        mnuCrearMateria = new javax.swing.JMenuItem();
        mnuListarMaterias = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jfrmLogin.setTitle("Login");
        jfrmLogin.setVisible(true);

        jLabel1.setText("*Correro Eletrónico:");

        jLabel2.setText("*Contraseña:");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jfrmLoginLayout = new javax.swing.GroupLayout(jfrmLogin.getContentPane());
        jfrmLogin.getContentPane().setLayout(jfrmLoginLayout);
        jfrmLoginLayout.setHorizontalGroup(
            jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmLoginLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(txtCorreo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfrmLoginLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(btnIngresar)
                .addGap(240, 240, 240))
        );
        jfrmLoginLayout.setVerticalGroup(
            jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfrmLoginLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jfrmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnIngresar)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        desktopPane.add(jfrmLogin);
        jfrmLogin.setBounds(190, 90, 570, 310);

        mnuEjercicioLogin.setMnemonic('f');
        mnuEjercicioLogin.setText("Archivo");
        mnuEjercicioLogin.setEnabled(false);

        mnuCrearEstudiante.setMnemonic('o');
        mnuCrearEstudiante.setText("Crear Estudiante");
        mnuEjercicioLogin.add(mnuCrearEstudiante);

        mnuListarEstudiantes.setMnemonic('s');
        mnuListarEstudiantes.setText("Listar Estudiantes");
        mnuEjercicioLogin.add(mnuListarEstudiantes);

        mnuMaterias.setText("Materias");

        mnuCrearMateria.setMnemonic('a');
        mnuCrearMateria.setText("Crear Materia");
        mnuMaterias.add(mnuCrearMateria);

        mnuListarMaterias.setText("Listar Materias");
        mnuMaterias.add(mnuListarMaterias);

        mnuEjercicioLogin.add(mnuMaterias);

        mnuCerrarSesion.setText("Cerrar Sesión");
        mnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarSesionActionPerformed(evt);
            }
        });
        mnuEjercicioLogin.add(mnuCerrarSesion);

        mnuSalir.setMnemonic('x');
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuEjercicioLogin.add(mnuSalir);

        menuBar.add(mnuEjercicioLogin);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        if (txtCorreo.getText() == null || txtCorreo.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe diligenciar el correo", "Datos Faltantes", 2);
        } else if (txtContrasenia.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this,
                    "Debe diligenciar la contraseña", "Datos Faltantes", 2);
        } else {
            //Significa que diligencio correo y contraseña
            Pattern pattern = Pattern.compile("^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$");
            Matcher matcher = pattern.matcher(txtCorreo.getText());

            if (matcher.find() == true) {
                usuarioAutenticado = controlLogin.
                        encontrarUsuario(txtCorreo.getText(), txtContrasenia.getText());
                if (usuarioAutenticado == null) {
                    JOptionPane.showMessageDialog(this,
                            "El usuario Ingresado no existe", "Datos Erróneos", 0);
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Bienvenido " + usuarioAutenticado, "Bienvenido", 1);
                    mnuEjercicioLogin.setEnabled(true);
                    gestionarPermisosMenu();
                    jfrmLogin.hide();
                }
            } else {
                 JOptionPane.showMessageDialog(this,
                            "El correo no tiene un formato válido", "Datos Erróneos", 0);
                
            }

        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSesionActionPerformed
        // TODO add your handling code here:
        mnuEjercicioLogin.setEnabled(false);
        txtCorreo.setText("");
        txtContrasenia.setText("");
        usuarioAutenticado = null;
        iniciarMenus(false);
        jfrmLogin.show();
        
    }//GEN-LAST:event_mnuCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIEjemploLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIEjemploLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIEjemploLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIEjemploLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIEjemploLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JInternalFrame jfrmLogin;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenuItem mnuCrearEstudiante;
    private javax.swing.JMenuItem mnuCrearMateria;
    private javax.swing.JMenu mnuEjercicioLogin;
    private javax.swing.JMenuItem mnuListarEstudiantes;
    private javax.swing.JMenuItem mnuListarMaterias;
    private javax.swing.JMenu mnuMaterias;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables

}
